name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Repo Structure
      run: ls -R

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install, Build and Test (Correct Path)
      run: |
        cd "04.Exercise-Continuous-Integration-Resources/01-Student-Registry-App"
        npm ci
        npm run build --if-present
        npm test
